include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Style rules
    directives_ordering: true
    prefer_single_quotes: true
    always_declare_return_types: true
    require_trailing_commas: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_final_fields: true
    sort_constructors_first: true
    sort_pub_dependencies: true
    sort_unnamed_constructors_first: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_this: true

    # Error prevention rules
    avoid_print: true
    avoid_dynamic_calls: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    avoid_web_libraries_in_flutter: true
    cancel_subscriptions: true
    close_sinks: true
    collection_methods_unrelated_type: true
    empty_statements: true
    unnecessary_statements: true

    # Flutter specific rules
    use_key_in_widget_constructors: true
    use_build_context_synchronously: true
    sized_box_for_whitespace: true

    # OOP rules
    annotate_overrides: true
    avoid_as: true
    camel_case_extensions: true
    camel_case_types: true
    file_names: true
    implementation_imports: true
    library_names: true
    library_prefixes: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_mixin: true
    package_names: true
    use_to_and_as_if_applicable: true
    null_closures: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/di.config.dart"
  errors:
    invalid_annotation_target: ignore
    directives_ordering: error
    prefer_single_quotes: error
    always_declare_return_types: error
    require_trailing_commas: error
    avoid_print: error
    avoid_dynamic_calls: error
    cancel_subscriptions: error
    close_sinks: error
    collection_methods_unrelated_type: error
    empty_statements: error
    unnecessary_statements: error
    use_key_in_widget_constructors: error
    annotate_overrides: error
    avoid_as: error
    camel_case_extensions: error
    camel_case_types: error
    file_names: error
    implementation_imports: ignore
    library_names: error
    library_prefixes: error
    prefer_is_empty: error
    prefer_is_not_empty: error
    prefer_mixin: error
    prefer_const_constructors: error
    sort_constructors_first: error
    package_names: error
    use_to_and_as_if_applicable: error
    must_call_super: ignore
