name: anivsub
description: "A Flutter application for anime streaming."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  archive: ^3.6.1
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  collection: ^1.18.0
  comment_tree: ^0.3.0
  cookie_jar: ^4.0.8
  crypto: ^3.0.6
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.1
  dio_cookie_manager: ^3.1.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_inappwebview: ^6.1.5
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  flutter_typeahead: ^5.2.0
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  get_it: ^8.0.3
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  html: ^0.15.5
  infinite_scroll_pagination: ^4.1.0
  injectable: ^2.5.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  path_provider: ^2.1.5
  pointycastle: ^3.9.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.1
  river_player: ^0.1.4
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.3.4
  skeletonizer: ^1.4.2
  supabase_flutter: ^2.8.2
  video_player: ^2.9.2
  wasm_run_flutter: ^0.1.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.4
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  injectable_generator: ^2.6.2
  json_serializable: ^6.9.0
  retrofit_generator: ^9.1.5

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/wasm/dha.wasm
    - .env
