name: anivsub
description: "A feature-rich Flutter application for anime streaming."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  get_it: ^8.0.1
  gap: ^3.0.1
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  go_router: ^14.3.0
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  geolocator: ^13.0.1
  equatable: ^2.0.5
  video_player: ^2.9.2
  injectable: ^2.5.0
  html: ^0.15.4
  cached_network_image: ^3.4.1
  river_player: ^0.1.3
  infinite_scroll_pagination: ^4.0.0
  flutter_typeahead: ^5.2.0
  crypto: ^3.0.6
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  path_provider: ^2.1.4
  supabase_flutter: ^2.8.0
  dio_cache_interceptor: ^3.5.0
  skeletonizer: ^1.4.2
  uuid: ^4.5.1
  flutter_dotenv: ^5.2.1
  dio_http2_adapter: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.5.7
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.3
  flutter_native_splash: ^2.4.2
  flutter_launcher_icons: ^0.14.1
  injectable_generator: ^2.6.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env