name: anivsub
description: "A Flutter application for anime streaming."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  # Flutter SDK packages
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management & DI
  get_it: ^8.0.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  injectable: ^2.5.0

  # Navigation
  go_router: ^14.4.1

  # Storage
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.2
  path_provider: ^2.1.5

  # Networking & API
  dio: ^5.7.0
  retrofit: ^4.4.1
  pretty_dio_logger: ^1.4.0
  dio_cookie_manager: ^3.1.1
  dio_cache_interceptor: ^3.5.0
  cookie_jar: ^4.0.8
  supabase_flutter: ^2.8.0

  # UI Components & Styling
  gap: ^3.0.1
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  infinite_scroll_pagination: ^4.1.0
  flutter_typeahead: ^5.2.0
  skeletonizer: ^1.4.2
  comment_tree: ^0.3.0
  flutter_inappwebview: ^6.1.5
  scrollable_positioned_list: ^0.3.8

  # Video Player
  video_player: ^2.9.2
  river_player: ^0.1.3

  # Data Handling & Serialization
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  equatable: ^2.0.5
  html: ^0.15.5
  intl: ^0.19.0
  collection: ^1.18.0

  # Security & Encryption
  crypto: ^3.0.6
  archive: ^3.6.1
  pointycastle: ^3.9.1

  # Configuration
  flutter_dotenv: ^5.2.1
  logger: ^2.4.0

  # WebAssembly
  wasm_run_flutter:
    git:
      url: https://github.com/phd051199/wasm_run.git
      ref: fix-namespace
      path: packages/wasm_run_flutter

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter

  # Code Generation & Build Tools
  freezed: ^2.5.7
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.4
  injectable_generator: ^2.6.2

  # Development Tools
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.2
  flutter_launcher_icons: ^0.14.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/wasm/dha.wasm
    - .env
