name: anivsub
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: any
  get_it: ^8.0.0
  gap: ^3.0.1
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  go_router: ^14.2.8
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  geolocator: ^13.0.1
  equatable: ^2.0.5
  lottie: ^3.1.2
  chewie: ^1.8.5
  video_player: ^2.9.2
  injectable: ^2.5.0
  html: ^0.15.4
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  better_player: ^0.0.84

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.5.7
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.2
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.1
  injectable_generator: ^2.6.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/json/
